FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libicu-dev libzip-dev unzip git \
 && docker-php-ext-install mysqli \
 && pecl install igbinary redis \
 && docker-php-ext-enable igbinary redis mysqli \
 && rm -rf /var/lib/apt/lists/* /tmp/pear

# 如需：
# RUN docker-php-ext-install intl zip

WORKDIR /var/www/html
EXPOSE 9000
CMD ["php-fpm"]

